# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Ev'), (1, 'End\xfcstriyel')], default=0, verbose_name='Hesap Tipi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to=settings.AUTH_USER_MODEL, verbose_name='Kullan\u0131c\u0131')),
            ],
            options={
                'verbose_name': 'Hesap',
                'verbose_name_plural': 'Hesaplar',
            },
        ),
        migrations.CreateModel(
            name='Crons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Sal\u0131'), (2, '\xc7ar\u015famba'), (3, 'Per\u015fembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Uygulanacak G\xfcnler')),
                ('switch_on_time', models.TimeField(verbose_name='A\xe7ma Zaman')),
                ('switch_off_time', models.TimeField(verbose_name='Kapama Zaman')),
            ],
            options={
                'verbose_name': 'Zamanlama',
                'verbose_name_plural': 'Zamanlamalar',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('relay_current', 'Ak\u0131m Sens\xf6rl\xfc 16 R\xf6le Kart\u0131'), ('relay', '16 R\xf6le Kart\u0131'), ('ir', 'IR Mod\xfcle')], max_length=15, verbose_name='Cihaz Tipi')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Cihaz Ad\u0131')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Cihaz Tan\u0131m\u0131')),
                ('wan_ip', models.CharField(default='0.0.0.0', max_length=50, verbose_name='WAN IP adresi')),
                ('ip', models.CharField(default='0.0.0.0', max_length=50, verbose_name='LAN IP adresi')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('status', models.BooleanField(default=True, verbose_name='Durum')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to='customers.Accounts', verbose_name='Hesap')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
            },
        ),
        migrations.CreateModel(
            name='IrButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Buton Ad\u0131')),
                ('icon', models.CharField(choices=[('light', 'Amp\xfcl'), ('aircond', 'Klima'), ('fan', 'Havaland\u0131rma'), ('watervalve', 'Su Vanas\u0131'), ('gas', 'Gaz Vanas\u0131'), ('blinds', 'Pajnur'), ('television', 'Televizyon'), ('satellite', 'Uydu'), ('digitalreceiver', 'Dijital Yay\u0131n'), ('musicbox', 'M\xfczik Seti'), ('projector', 'Projekt\xf6r'), ('dvdplayer', 'DVD Oynat\u0131c\u0131'), ('camera', 'Kamera')], max_length=20, verbose_name='Simge')),
                ('ir_type', models.CharField(max_length=20, verbose_name='IR Tipi')),
                ('ir_code', models.CharField(max_length=16, verbose_name='IR Code')),
                ('ir_bits', models.IntegerField(verbose_name='Bits')),
            ],
            options={
                'verbose_name': 'IR Buton',
                'verbose_name_plural': 'IR Butonlar\u0131',
            },
        ),
        migrations.CreateModel(
            name='IrRemote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Uzaktan Kumanda Ad\u0131')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IrButtons', to='customers.Devices', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'IR Kumanda',
                'verbose_name_plural': 'IR Kumandalar',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hesaba ba\u011fl\u0131 cihazlar\u0131n kurulaca\u011f\u0131 adresin konumu i\xe7in isimlendirme', max_length=50, verbose_name='Konum Ad\u0131')),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Enlem')),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Boylam')),
                ('account', models.ForeignKey(help_text='Konumun ba\u011flanaca\u011f\u0131 hesap', on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='customers.Accounts', verbose_name='Hesap')),
            ],
            options={
                'verbose_name': 'Konum',
                'verbose_name_plural': 'Konumlar',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=1, verbose_name='Donan\u0131m Limiti')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('expired', 'Sona erdi'), ('canceled', '\u0130ptal Edildi')], default='pending', max_length=15, verbose_name='Durum')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plans', to='customers.Accounts', verbose_name='Hesap')),
            ],
            options={
                'verbose_name': '\xdcyelik',
                'verbose_name_plural': '\xdcyelik',
            },
        ),
        migrations.CreateModel(
            name='RelayCurrentValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ak\u0131m De\u011feri (Amper)')),
                ('power_cons', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kullan\u0131lan G\xfc\xe7 (Watt/saat)')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'R\xf6le Ak\u0131m De\u011feri',
                'verbose_name_plural': 'R\xf6le Ak\u0131m De\u011ferleri',
            },
        ),
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='R\xf6le Tan\u0131m\u0131')),
                ('pressed', models.BooleanField(default=False, verbose_name='Bas\u0131l\u0131 m\u0131?')),
                ('relay_no', models.IntegerField(verbose_name='R\xf6le No')),
                ('type', models.CharField(choices=[('switch', 'A\xe7 / Kapat'), ('push', 'Bas - \xe7ek'), ('count', 'Geri Say\u0131m'), ('scheduled', 'Zamanlanm\u0131\u015f')], max_length=20, verbose_name='Anahtar Tipi')),
                ('icon', models.CharField(choices=[('light', 'Amp\xfcl'), ('aircond', 'Klima'), ('fan', 'Havaland\u0131rma'), ('watervalve', 'Su Vanas\u0131'), ('gas', 'Gaz Vanas\u0131'), ('blinds', 'Pajnur'), ('television', 'Televizyon'), ('satellite', 'Uydu'), ('digitalreceiver', 'Dijital Yay\u0131n'), ('musicbox', 'M\xfczik Seti'), ('projector', 'Projekt\xf6r'), ('dvdplayer', 'DVD Oynat\u0131c\u0131'), ('camera', 'Kamera')], max_length=20, verbose_name='Simge')),
                ('total_instant_current', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Anl\u0131k Ak\u0131m')),
                ('total_instant_power', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Anl\u0131k Watt')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relays', to='customers.Devices', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'R\xf6le',
                'verbose_name_plural': 'R\xf6leler',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Oda Tan\u0131m\u0131')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms', to='customers.Accounts', verbose_name='Hesap')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms', to='customers.Locations', verbose_name='Konum')),
            ],
            options={
                'verbose_name': 'Odalar',
                'verbose_name_plural': 'Oda',
            },
        ),
        migrations.AddField(
            model_name='relays',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relays', to='customers.Rooms', verbose_name='Oda'),
        ),
        migrations.AddField(
            model_name='relaycurrentvalues',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrentValues', to='customers.Relays', verbose_name='R\xf6le'),
        ),
        migrations.AddField(
            model_name='irremote',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IrButtons', to='customers.Rooms', verbose_name='Oda'),
        ),
        migrations.AddField(
            model_name='irbutton',
            name='ir_remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IrButtons', to='customers.IrRemote', verbose_name='Kumanda'),
        ),
        migrations.AddField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to='customers.Rooms'),
        ),
        migrations.AddField(
            model_name='crons',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Crons', to='customers.Relays', verbose_name='R\xf6le'),
        ),
    ]
