# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to=settings.AUTH_USER_MODEL, verbose_name='Kullan\u0131c\u0131')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cihaz Tan\u0131m\u0131')),
                ('ip', models.CharField(max_length=50, verbose_name='IP adresi')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to='customers.Accounts', verbose_name='Hesap')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lokasyon Tan\u0131m\u0131')),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Enlem')),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Boylam')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='customers.Accounts', verbose_name='Hesap')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=1, verbose_name='Donan\u0131m Limiti')),
                ('status', models.CharField(choices=[('pending', 'Belemede'), ('active', 'Aktif'), ('expired', 'Sona erdi'), ('canceled', '\u0130ptal Edildi')], default='pending', max_length=15, verbose_name='Durum')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plans', to='customers.Accounts', verbose_name='Hesap')),
            ],
        ),
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='R\xf6le Tan\u0131m\u0131')),
                ('relay_no', models.IntegerField(verbose_name='R\xf6le No')),
                ('type', models.CharField(max_length=20, verbose_name='Anahtar Tipi')),
                ('icon', models.CharField(choices=[('light', 'Amp\xfcl'), ('aircond', 'Klima'), ('fan', 'Fan')], max_length=20, verbose_name='Simge')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relays', to='customers.Accounts', verbose_name='Cihaz')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms', to='customers.Accounts', verbose_name='Hesap')),
            ],
        ),
        migrations.AddField(
            model_name='relays',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relays', to='customers.Rooms', verbose_name='Oda'),
        ),
    ]
