# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='salon', max_length=50, verbose_name='Oda Tan\u0131m\u0131'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plans',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('expired', 'Sona erdi'), ('canceled', '\u0130ptal Edildi')], default='pending', max_length=15, verbose_name='Durum'),
        ),
    ]
