# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170418_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relays',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relays', to='customers.Devices', verbose_name='Cihaz'),
        ),
    ]
