# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20170418_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='relays',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Geri Say\u0131m - dakika'),
        ),
        migrations.AddField(
            model_name='relays',
            name='days',
            field=models.CharField(default='0000000', max_length=7, verbose_name='Uygulanacak G\xfcnler'),
        ),
        migrations.AddField(
            model_name='relays',
            name='finish_day',
            field=models.DateField(blank=True, null=True, verbose_name='Biti\u015f Tarihi'),
        ),
        migrations.AddField(
            model_name='relays',
            name='start_day',
            field=models.DateField(blank=True, null=True, verbose_name='Ba\u015flama Tarihi'),
        ),
        migrations.AddField(
            model_name='relays',
            name='switch_off_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Kapama Zaman'),
        ),
        migrations.AddField(
            model_name='relays',
            name='switch_on_time',
            field=models.TimeField(blank=True, null=True, verbose_name='A\xe7ma Zaman'),
        ),
        migrations.AlterField(
            model_name='relays',
            name='type',
            field=models.CharField(choices=[('switch', 'A\xe7 / Kapat'), ('push', 'Bas - \xe7ek'), ('count', 'Geri Say\u0131m'), ('scheduled', 'Zamanlanm\u0131\u015f')], max_length=20, verbose_name='Anahtar Tipi'),
        ),
    ]
