# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20170418_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='relays',
            name='pressed',
            field=models.BooleanField(default=False, verbose_name='Bas\u0131l\u0131 m\u0131?'),
        ),
    ]
